[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tracer"
version = "0.0.1"
requires-python = ">=3.7"
license = {text = "MIT"}

[tool.setuptools.packages.find]
where = ["src"]